// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: nekotvstate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoTimer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsStarted      bool                   `protobuf:"varint,1,opt,name=is_started,json=isStarted,proto3" json:"is_started,omitempty"`
	StartTime      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	PauseStartTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=pause_start_time,json=pauseStartTime,proto3" json:"pause_start_time,omitempty"`
	RateStartTime  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=rate_start_time,json=rateStartTime,proto3" json:"rate_start_time,omitempty"`
	Rate           float32                `protobuf:"fixed32,5,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VideoTimer) Reset() {
	*x = VideoTimer{}
	mi := &file_nekotvstate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoTimer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoTimer) ProtoMessage() {}

func (x *VideoTimer) ProtoReflect() protoreflect.Message {
	mi := &file_nekotvstate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoTimer.ProtoReflect.Descriptor instead.
func (*VideoTimer) Descriptor() ([]byte, []int) {
	return file_nekotvstate_proto_rawDescGZIP(), []int{0}
}

func (x *VideoTimer) GetIsStarted() bool {
	if x != nil {
		return x.IsStarted
	}
	return false
}

func (x *VideoTimer) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *VideoTimer) GetPauseStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PauseStartTime
	}
	return nil
}

func (x *VideoTimer) GetRateStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RateStartTime
	}
	return nil
}

func (x *VideoTimer) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type ServerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoList     []*VideoItem           `protobuf:"bytes,1,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	ItemPos       int32                  `protobuf:"varint,2,opt,name=item_pos,json=itemPos,proto3" json:"item_pos,omitempty"`
	Timer         *VideoTimer            `protobuf:"bytes,3,opt,name=timer,proto3" json:"timer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	mi := &file_nekotvstate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_nekotvstate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_nekotvstate_proto_rawDescGZIP(), []int{1}
}

func (x *ServerState) GetVideoList() []*VideoItem {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *ServerState) GetItemPos() int32 {
	if x != nil {
		return x.ItemPos
	}
	return 0
}

func (x *ServerState) GetTimer() *VideoTimer {
	if x != nil {
		return x.Timer
	}
	return nil
}

var File_nekotvstate_proto protoreflect.FileDescriptor

const file_nekotvstate_proto_rawDesc = "" +
	"\n" +
	"\x11nekotvstate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fnekotv.proto\"\x84\x02\n" +
	"\n" +
	"VideoTimer\x12\x1d\n" +
	"\n" +
	"is_started\x18\x01 \x01(\bR\tisStarted\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12D\n" +
	"\x10pause_start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0epauseStartTime\x12B\n" +
	"\x0frate_start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rrateStartTime\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x02R\x04rate\"v\n" +
	"\vServerState\x12)\n" +
	"\n" +
	"video_list\x18\x01 \x03(\v2\n" +
	".VideoItemR\tvideoList\x12\x19\n" +
	"\bitem_pos\x18\x02 \x01(\x05R\aitemPos\x12!\n" +
	"\x05timer\x18\x03 \x01(\v2\v.VideoTimerR\x05timerB\x06Z\x04./pbb\x06proto3"

var (
	file_nekotvstate_proto_rawDescOnce sync.Once
	file_nekotvstate_proto_rawDescData []byte
)

func file_nekotvstate_proto_rawDescGZIP() []byte {
	file_nekotvstate_proto_rawDescOnce.Do(func() {
		file_nekotvstate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nekotvstate_proto_rawDesc), len(file_nekotvstate_proto_rawDesc)))
	})
	return file_nekotvstate_proto_rawDescData
}

var file_nekotvstate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nekotvstate_proto_goTypes = []any{
	(*VideoTimer)(nil),            // 0: VideoTimer
	(*ServerState)(nil),           // 1: ServerState
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*VideoItem)(nil),             // 3: VideoItem
}
var file_nekotvstate_proto_depIdxs = []int32{
	2, // 0: VideoTimer.start_time:type_name -> google.protobuf.Timestamp
	2, // 1: VideoTimer.pause_start_time:type_name -> google.protobuf.Timestamp
	2, // 2: VideoTimer.rate_start_time:type_name -> google.protobuf.Timestamp
	3, // 3: ServerState.video_list:type_name -> VideoItem
	0, // 4: ServerState.timer:type_name -> VideoTimer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_nekotvstate_proto_init() }
func file_nekotvstate_proto_init() {
	if File_nekotvstate_proto != nil {
		return
	}
	file_nekotv_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nekotvstate_proto_rawDesc), len(file_nekotvstate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nekotvstate_proto_goTypes,
		DependencyIndexes: file_nekotvstate_proto_depIdxs,
		MessageInfos:      file_nekotvstate_proto_msgTypes,
	}.Build()
	File_nekotvstate_proto = out.File
	file_nekotvstate_proto_goTypes = nil
	file_nekotvstate_proto_depIdxs = nil
}
